// Code generated by "stringer --type TestAttr --tags test"; DO NOT EDIT.

package entitynodetest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[I8-0]
	_ = x[PI8-1]
	_ = x[I16-2]
	_ = x[PI16-3]
	_ = x[I32-4]
	_ = x[PI32-5]
	_ = x[I64-6]
	_ = x[PI64-7]
	_ = x[UI8-8]
	_ = x[PUI8-9]
	_ = x[UI16-10]
	_ = x[PUI16-11]
	_ = x[UI32-12]
	_ = x[PUI32-13]
	_ = x[UI64-14]
	_ = x[PUI64-15]
	_ = x[String-16]
	_ = x[PS-17]
	_ = x[Uintptr-18]
	_ = x[PUintptr-19]
	_ = x[E-20]
	_ = x[L-21]
	_ = x[R-22]
	_ = x[N-23]
}

const _TestAttr_name = "I8PI8I16PI16I32PI32I64PI64UI8PUI8UI16PUI16UI32PUI32UI64PUI64StringPSUintptrPUintptrELRN"

var _TestAttr_index = [...]uint8{0, 2, 5, 8, 12, 15, 19, 22, 26, 29, 33, 37, 42, 46, 51, 55, 60, 66, 68, 75, 83, 84, 85, 86, 87}

func (i TestAttr) String() string {
	if i < 0 || i >= TestAttr(len(_TestAttr_index)-1) {
		return "TestAttr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestAttr_name[_TestAttr_index[i]:_TestAttr_index[i+1]]
}
