// Code generated by "stringer --type testAttr --tags test"; DO NOT EDIT.

package entitynodetest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[i8-0]
	_ = x[pi8-1]
	_ = x[i16-2]
	_ = x[pi16-3]
	_ = x[i32-4]
	_ = x[pi32-5]
	_ = x[i64-6]
	_ = x[pi64-7]
	_ = x[ui8-8]
	_ = x[pui8-9]
	_ = x[ui16-10]
	_ = x[pui16-11]
	_ = x[ui32-12]
	_ = x[pui32-13]
	_ = x[ui64-14]
	_ = x[pui64-15]
	_ = x[str-16]
	_ = x[pstr-17]
	_ = x[_uintptr-18]
	_ = x[puintptr-19]
	_ = x[value-20]
	_ = x[left-21]
	_ = x[right-22]
}

const _TestAttr_name = "i8pi8i16pi16i32pi32i64pi64ui8pui8ui16pui16ui32pui32ui64pui64strpstr_uintptrpuintptrvalueleftright"

var _TestAttr_index = [...]uint8{0, 2, 5, 8, 12, 15, 19, 22, 26, 29, 33, 37, 42, 46, 51, 55, 60, 63, 67, 75, 83, 88, 92, 97}

func (i testAttr) String() string {
	if i < 0 || i >= testAttr(len(_TestAttr_index)-1) {
		return "testAttr(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TestAttr_name[_TestAttr_index[i]:_TestAttr_index[i+1]]
}
