// Code generated by "stringer -type ReproposalReason"; DO NOT EDIT.

package replication

import "strconv"

const _ReproposalReason_name = "NoReasonReasonNewLeaderReasonNewLeaderOrConfigChangeReasonSnapshotAppliedReasonReplicaIDChangedReasonTicks"

var _ReproposalReason_index = [...]uint8{0, 8, 23, 52, 73, 95, 106}

func (i ReproposalReason) String() string {
	if i < 0 || i >= ReproposalReason(len(_ReproposalReason_index)-1) {
		return "ReproposalReason(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ReproposalReason_name[_ReproposalReason_index[i]:_ReproposalReason_index[i+1]]
}
