// Code generated by "stringer -type=Method"; DO NOT EDIT.

package kvtoypb

import "strconv"

const _Method_name = "GetPutConditionalPutDelete"

var _Method_index = [...]uint8{0, 3, 6, 20, 26}

func (i Method) String() string {
	if i < 0 || i >= Method(len(_Method_index)-1) {
		return "Method(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Method_name[_Method_index[i]:_Method_index[i+1]]
}
