// Code generated by "stringer -type systemAttribute"; DO NOT EDIT.

package rel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Type-63]
	_ = x[Self-62]
}

const _SystemAttribute_name = "SelfType"

var _SystemAttribute_index = [...]uint8{0, 4, 8}

func (i systemAttribute) String() string {
	i -= 62
	if i < 0 || i >= systemAttribute(len(_SystemAttribute_index)-1) {
		return "systemAttribute(" + strconv.FormatInt(int64(i+62), 10) + ")"
	}
	return _SystemAttribute_name[_SystemAttribute_index[i]:_SystemAttribute_index[i+1]]
}
