// Code generated by "stringer -type SystemAttribute"; DO NOT EDIT.

package rel

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant valuesMap have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeAttribute-63]
	_ = x[IDAttribute-62]
}

const _SystemAttribute_name = "IDAttributeTypeAttribute"

var _SystemAttribute_index = [...]uint8{0, 11, 24}

func (i SystemAttribute) String() string {
	i -= 62
	if i < 0 || i >= SystemAttribute(len(_SystemAttribute_index)-1) {
		return "SystemAttribute(" + strconv.FormatInt(int64(i+62), 10) + ")"
	}
	return _SystemAttribute_name[_SystemAttribute_index[i]:_SystemAttribute_index[i+1]]
}
